_target_: innofw.core.datamodules.lightning_datamodules.semantic_segmentation.tiff_dm.SegmentationDM
# ${.root}
train:
  source: /mnt/localssd/lada/innofw/data/130323/train

test:
  source: /mnt/localssd/lada/innofw/data/130323/test

# weights_csv_path: /mnt/nvmestorage/qb/data_n_weights/linear-road-bin-seg-oftp/301122/processed/070123-167folders-2048/weights.csv

num_workers: 32
batch_size: 16
channels: 3


name: oks
task: image-segmentation
description: some
markup_info: some
date_time: some